/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as WorkspaceRouteRouteImport } from './routes/workspace/route'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceElevationRouteImport } from './routes/workspace/elevation'
import { Route as WorkspaceExportRouteImport } from './routes/workspace/export'
import { Route as WorkspaceMeasurementsRouteImport } from './routes/workspace/measurements'
import { Route as WorkspaceUploadRouteImport } from './routes/workspace/upload'
import { Route as WorkspaceValidationRouteImport } from './routes/workspace/validation'
import { Route as WorkspaceViewerRouteImport } from './routes/workspace/viewer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceElevationRoute = WorkspaceElevationRouteImport.update({
  id: '/elevation',
  path: '/elevation',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceExportRoute = WorkspaceExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceMeasurementsRoute = WorkspaceMeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceUploadRoute = WorkspaceUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceValidationRoute = WorkspaceValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceViewerRoute = WorkspaceViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/technology': typeof TechnologyRoute
  '/workspace/elevation': typeof WorkspaceElevationRoute
  '/workspace/export': typeof WorkspaceExportRoute
  '/workspace/measurements': typeof WorkspaceMeasurementsRoute
  '/workspace/upload': typeof WorkspaceUploadRoute
  '/workspace/validation': typeof WorkspaceValidationRoute
  '/workspace/viewer': typeof WorkspaceViewerRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/technology': typeof TechnologyRoute
  '/workspace/elevation': typeof WorkspaceElevationRoute
  '/workspace/export': typeof WorkspaceExportRoute
  '/workspace/measurements': typeof WorkspaceMeasurementsRoute
  '/workspace/upload': typeof WorkspaceUploadRoute
  '/workspace/validation': typeof WorkspaceValidationRoute
  '/workspace/viewer': typeof WorkspaceViewerRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/technology': typeof TechnologyRoute
  '/workspace/elevation': typeof WorkspaceElevationRoute
  '/workspace/export': typeof WorkspaceExportRoute
  '/workspace/measurements': typeof WorkspaceMeasurementsRoute
  '/workspace/upload': typeof WorkspaceUploadRoute
  '/workspace/validation': typeof WorkspaceValidationRoute
  '/workspace/viewer': typeof WorkspaceViewerRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace'
    | '/auth'
    | '/technology'
    | '/workspace/elevation'
    | '/workspace/export'
    | '/workspace/measurements'
    | '/workspace/upload'
    | '/workspace/validation'
    | '/workspace/viewer'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/technology'
    | '/workspace/elevation'
    | '/workspace/export'
    | '/workspace/measurements'
    | '/workspace/upload'
    | '/workspace/validation'
    | '/workspace/viewer'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/workspace'
    | '/auth'
    | '/technology'
    | '/workspace/elevation'
    | '/workspace/export'
    | '/workspace/measurements'
    | '/workspace/upload'
    | '/workspace/validation'
    | '/workspace/viewer'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/elevation': {
      id: '/workspace/elevation'
      path: '/elevation'
      fullPath: '/workspace/elevation'
      preLoaderRoute: typeof WorkspaceElevationRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/export': {
      id: '/workspace/export'
      path: '/export'
      fullPath: '/workspace/export'
      preLoaderRoute: typeof WorkspaceExportRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/measurements': {
      id: '/workspace/measurements'
      path: '/measurements'
      fullPath: '/workspace/measurements'
      preLoaderRoute: typeof WorkspaceMeasurementsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/upload': {
      id: '/workspace/upload'
      path: '/upload'
      fullPath: '/workspace/upload'
      preLoaderRoute: typeof WorkspaceUploadRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/validation': {
      id: '/workspace/validation'
      path: '/validation'
      fullPath: '/workspace/validation'
      preLoaderRoute: typeof WorkspaceValidationRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/viewer': {
      id: '/workspace/viewer'
      path: '/viewer'
      fullPath: '/workspace/viewer'
      preLoaderRoute: typeof WorkspaceViewerRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceElevationRoute: typeof WorkspaceElevationRoute
  WorkspaceExportRoute: typeof WorkspaceExportRoute
  WorkspaceMeasurementsRoute: typeof WorkspaceMeasurementsRoute
  WorkspaceUploadRoute: typeof WorkspaceUploadRoute
  WorkspaceValidationRoute: typeof WorkspaceValidationRoute
  WorkspaceViewerRoute: typeof WorkspaceViewerRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceElevationRoute: WorkspaceElevationRoute,
  WorkspaceExportRoute: WorkspaceExportRoute,
  WorkspaceMeasurementsRoute: WorkspaceMeasurementsRoute,
  WorkspaceUploadRoute: WorkspaceUploadRoute,
  WorkspaceValidationRoute: WorkspaceValidationRoute,
  WorkspaceViewerRoute: WorkspaceViewerRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
